---
name: DNF CI
on: pull_request_target

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      options: --privileged
    steps:
      - name: Check out ci-dnf-stack
        uses: actions/checkout@v2
        with:
          repository: rpm-software-management/ci-dnf-stack

      - name: Setup CI
        id: setup-ci
        uses: ./.github/actions/setup-ci
        with:
          copr-user: ${{secrets.COPR_USER}}
          copr-api-token: ${{secrets.COPR_API_TOKEN}}
          setup-integration-testing: true

      - name: Check out sources
        uses: actions/checkout@v2
        with:
          path: gits/${{github.event.pull_request.head.repo.name}}
          ref: ${{github.event.pull_request.head.sha}}  # check out the PR HEAD
          fetch-depth: 0

      - name: Run CI
        uses: ./.github/actions/run-ci
        with:
          copr-user: ${{steps.setup-ci.outputs.copr-user}}
